import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  Activity, BookOpen, Check, ChevronDown, Clipboard, Cloud, Command, Copy, Download, ExternalLink, FileText,
  Gauge, History, Home, Info, Keyboard, Lightbulb, Mic, Moon, MoreHorizontal, Plus, Search, Settings,
  Sparkles, Sun, Trash2, User, Volume2, WandSparkles, Zap, ShieldCheck, X
} from "lucide-react";
import * as bridge from "./lib/bridge";
import { findSuggestions } from "./logic";
import BeeMark from "./BeeMark";
import type { AppConfig, DictionaryEntry, HistoryItem, ModelInfo, RecordingState, RuntimeSnapshot, Theme, UpdateInfo } from "./types";

type Page = "home"|"history"|"stats"|"dictionary"|"shortcuts"|"settings"|"subscription"|"suggestions"|"about";

const nav: {label:string;page:Page;icon:typeof Home}[] = [
  {label:"Home",page:"home",icon:Home},{label:"History",page:"history",icon:History},{label:"Statistics",page:"stats",icon:Activity},
  {label:"Dictionary",page:"dictionary",icon:BookOpen},{label:"Shortcuts",page:"shortcuts",icon:Keyboard},{label:"Settings",page:"settings",icon:Settings},
];

function Logo({small=false}:{small?:boolean}) { return <div className={`logo ${small?"small":""}`}><span className="logo-glyph"><BeeMark/></span>{!small&&<strong>Bee</strong>}</div>; }
function Button({children,kind="primary",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{kind?:"primary"|"secondary"|"ghost"|"danger"}){return <button className={`btn ${kind}`} {...props}>{children}</button>}
function Switch({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){return <button className={`switch ${checked?"on":""}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>}
function Select({value,onChange,children,label}:{value:string;onChange:(v:string)=>void;children:React.ReactNode;label:string}){return <label className="select-wrap"><span className="sr-only">{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select><ChevronDown size={14}/></label>}
function Kbd({children}:{children:React.ReactNode}){return <kbd>{children}</kbd>}

export default function App(){
  const [data,setData]=useState<RuntimeSnapshot|null>(null); const [page,setPage]=useState<Page>("home"); const [loading,setLoading]=useState(true); const [closeNotice,setCloseNotice]=useState(false); const [errorMessage,setErrorMessage]=useState("");
  const reload=async()=>{setData(await bridge.snapshot());setLoading(false)};
  useEffect(()=>{reload(); const clean=bridge.listenEvent("data-changed",()=>reload()); return()=>{clean.then(fn=>fn())}},[]);
  useEffect(()=>{const clean=bridge.listenEvent("close-to-tray-requested",()=>setCloseNotice(true));return()=>{clean.then(fn=>fn())}},[]);
  useEffect(()=>{const clean=bridge.listenEvent<string>("recording-error",setErrorMessage);return()=>{clean.then(fn=>fn())}},[]);
  useEffect(()=>{if(data) document.documentElement.dataset.theme=data.config.theme},[data?.config.theme]);
  const patch=async(next:Partial<AppConfig>)=>{const config=await bridge.updateConfig(next);setData(d=>d?{...d,config}:d)};
  if(loading||!data) return <div className="app-loading"><Logo/><span className="spinner"/></div>;
  if(!data.config.onboardingComplete) return <Onboarding data={data} onDone={async()=>{await patch({onboardingComplete:true});reload()}}/>;
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="traffic-spacer"/><Logo/>
      <nav className="main-nav">{nav.map(item=><button key={item.page} className={page===item.page?"active":""} onClick={()=>setPage(item.page)}><item.icon size={17}/><span>{item.label}</span>{item.page==="shortcuts"&&!data.config.pushToTalkKey&&<i className="notice-dot"/>}</button>)}</nav>
      <div className="sidebar-grow"/>
      <button className="credit-card" onClick={()=>setPage("subscription")}><span><Zap size={14}/> Credits</span><strong>1,250</strong></button>
      <nav className="secondary-nav"><button className={page==="suggestions"?"active":""} onClick={()=>setPage("suggestions")}><Lightbulb size={17}/>Suggestions</button><button className={page==="about"?"active":""} onClick={()=>setPage("about")}><Info size={17}/>About</button></nav>
      <button className="account-row" onClick={()=>setPage("subscription")}><span className="avatar"><User size={14}/></span><span><strong>Local user</strong><small>Free plan</small></span><MoreHorizontal size={16}/></button>
    </aside>
    <main className="content">
      {page==="home"&&<HomePage data={data} patch={patch} reload={reload}/>} {page==="history"&&<HistoryPage data={data} reload={reload}/>} {page==="stats"&&<StatsPage data={data}/>} {page==="dictionary"&&<DictionaryPage data={data} reload={reload} patch={patch}/>} {page==="shortcuts"&&<ShortcutsPage data={data} patch={patch}/>} {page==="settings"&&<SettingsPage data={data} patch={patch}/>} {page==="subscription"&&<SubscriptionPage/>} {page==="suggestions"&&<SuggestionsPage data={data} patch={patch} reload={reload}/>} {page==="about"&&<AboutPage version={data.version}/>} 
    </main>
    {errorMessage&&<div className="error-toast" role="alert"><span>!</span><div><strong>Dictation needs attention</strong><p>{errorMessage}</p></div><Button kind="ghost" onClick={()=>{setPage("settings");setErrorMessage("")}}>Settings</Button><button aria-label="Dismiss" onClick={()=>setErrorMessage("")}><X size={14}/></button></div>}
    {closeNotice&&<div className="modal-backdrop" role="presentation"><section className="close-modal" role="dialog" aria-modal="true" aria-labelledby="close-title"><span className="setting-icon"><Mic size={19}/></span><h2 id="close-title">Bee keeps listening for your shortcut</h2><p>Closing the dashboard leaves Bee running in the menu bar, so Fn / Globe still works in every app.</p><div><Button kind="ghost" onClick={()=>bridge.quitApp()}>Quit Bee</Button><Button onClick={async()=>{await bridge.acknowledgeCloseNotice();setCloseNotice(false)}}>Keep running</Button></div></section></div>}
  </div>
}

function PageHead({eyebrow,title,copy,action}:{eyebrow?:string;title:string;copy?:string;action?:React.ReactNode}){return <header className="page-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{action}</header>}

function HomePage({data,patch,reload}:{data:RuntimeSnapshot;patch:(x:Partial<AppConfig>)=>Promise<void>;reload:()=>Promise<void>}){
  const [recordingState,setRecordingState]=useState<RecordingState>("idle"); const recording=recordingState==="listening"; const active=data.models.find(m=>m.active)||data.models.find(m=>m.downloaded);useEffect(()=>{const clean=bridge.recordingEvents(state=>{setRecordingState(state);if(state==="success")setTimeout(reload,200)});return()=>{clean.then(fn=>fn())}},[]);
  const toggle=async()=>{try{if(recording){await bridge.stopRecording()}else if(recordingState!=="processing"){await bridge.startRecording()}}catch(error){console.error(error);setTimeout(reload,250)}};
  return <div className="page home-page"><PageHead eyebrow="Dashboard" title="Ready when you are." copy="Your voice becomes text wherever your cursor is blinking." action={<button disabled={recordingState==="processing"} className={`record-orb ${recording?"recording":""}`} onClick={toggle} aria-label={recording?"Stop recording":"Start recording"}><Mic size={20}/><span>{recording?"Stop":recordingState==="processing"?"Transcribing…":"Record"}</span></button>}/>
    <section className="status-strip"><div className="status-primary"><span className="status-icon"><Mic size={18}/></span><div><small>Push to talk</small><strong>{data.config.pushToTalkKey}</strong></div></div><div><small>Mode</small><strong>{data.config.transcriptionMode==="local"?<><span className="green-dot"/>Local · Private</>:<><Cloud size={13}/> Cloud · 99+ languages</>}</strong></div><div><small>Active model</small><strong>{active?.name||"No model downloaded"}</strong></div><button className="icon-btn"><MoreHorizontal size={18}/></button></section>
    <div className="home-grid"><section className="card quick-start"><div className="card-title"><span><Command size={17}/>How to dictate</span><small>THE WHOLE INTERFACE IS ONE KEY</small></div><ol><li><i>1</i><div><strong>Hold</strong><p>Hold {data.config.pushToTalkKey} in any app.</p></div></li><li><i>2</i><div><strong>Speak</strong><p>Say it naturally, like you would to a teammate.</p></div></li><li><i>3</i><div><strong>Release</strong><p>Your words land at the active cursor.</p></div></li></ol><button className="test-record" onClick={toggle}><span className={recording?"pulse":""}><Mic size={16}/></span>{recording?"Listening — release to finish":"Test your microphone"}</button></section>
      <section className="card mode-card"><div className="card-title"><span><Gauge size={17}/>Transcription</span></div><div className="segmented"><button className={data.config.transcriptionMode==="local"?"active":""} onClick={()=>patch({transcriptionMode:"local"})}><Moon size={14}/>Local</button><button className={data.config.transcriptionMode==="cloud"?"active":""} onClick={()=>patch({transcriptionMode:"cloud"})}><Cloud size={14}/>Cloud</button></div><div className="privacy-lock"><span><Check size={15}/></span><div><strong>{data.config.transcriptionMode==="local"?"Audio stays on this machine":"Encrypted cloud transcription"}</strong><p>{data.config.transcriptionMode==="local"?"Whisper and Parakeet run fully offline.":"Groq Whisper Large-v3-Turbo with auto language detection."}</p></div></div><div className="inline-setting"><span><small>Model</small><strong>{active?.name||"Choose a model"}</strong></span><button onClick={()=>document.getElementById("models")?.scrollIntoView({behavior:"smooth"})}>Manage</button></div></section>
    </div>
    <section className="section-block"><div className="block-heading"><div><h2>Recent transcriptions</h2><p>Saved privately on this device.</p></div><span>{data.history.length} total</span></div>{data.history.length?<div className="recent-list">{data.history.slice(0,3).map(item=><article key={item.id}><span className="source-badge">{item.source==="local"?<Moon size={13}/>:<Cloud size={13}/>}</span><div><p>{item.text}</p><small>{relative(item.timestamp)} · {item.wordCount} words · {item.durationSeconds.toFixed(1)}s</small></div><button onClick={()=>bridge.copyText(item.text)} aria-label="Copy"><Copy size={15}/></button></article>)}</div>:<Empty icon={History} title="Your words will appear here" copy="Finish a dictation to start building a private history."/>}</section>
    <div id="models"><ModelsPanel models={data.models} reload={reload}/></div>
  </div>
}

function ModelsPanel({models,reload}:{models:ModelInfo[];reload:()=>Promise<void>}){const [busy,setBusy]=useState<string|null>(null);const [progress,setProgress]=useState<Record<string,number>>({});useEffect(()=>{const clean=bridge.listenEvent<{modelId:string;percent:number}>("model-download",event=>setProgress(value=>({...value,[event.modelId]:event.percent})));return()=>{clean.then(fn=>fn())}},[]);const act=async(model:ModelInfo)=>{setBusy(model.id);try{if(!model.downloaded)await bridge.downloadModel(model.id);await bridge.selectModel(model.id);await reload()}finally{setBusy(null)}};const remove=async(model:ModelInfo)=>{if(!confirm(`Delete ${model.name} from this Mac?`))return;setBusy(model.id);try{await bridge.deleteModel(model.id);await reload()}finally{setBusy(null)}};return <section className="section-block model-section"><div className="block-heading"><div><h2>On-device models</h2><p>Download once. Dictate offline forever.</p></div><span>{models.filter(m=>m.downloaded).length} of {models.length} installed</span></div><div className="model-grid">{models.map(model=><article className={`model-card ${model.active?"selected":""}`} key={model.id}><div className="model-top"><span className="model-cube">{model.id.includes("parakeet")?"P":"W"}</span><div>{model.recommended&&<small className="recommended">RECOMMENDED</small>}<h3>{model.name}</h3><p>{model.detail}</p></div>{model.active?<span className="active-check"><Check size={12}/></span>:model.downloaded?<button className="model-delete" onClick={()=>remove(model)} aria-label={`Delete ${model.name}`}><Trash2 size={13}/></button>:null}</div>{busy===model.id&&<span className="download-track"><i style={{width:`${progress[model.id]||0}%`}}/></span>}<div className="model-foot"><span>{busy===model.id?`${Math.round(progress[model.id]||0)}%`:(model.sizeMb>=1000?`${(model.sizeMb/1000).toFixed(1)} GB`:`${model.sizeMb} MB`)}</span><Button kind={model.active?"ghost":"secondary"} disabled={!!busy||model.active} onClick={()=>act(model)}>{busy===model.id?<><span className="mini-spinner"/>Downloading</>:model.downloaded?(model.active?"Active":"Use model"):<><Download size={13}/> Download</>}</Button></div></article>)}</div></section>}

function HistoryPage({data,reload}:{data:RuntimeSnapshot;reload:()=>Promise<void>}){const [query,setQuery]=useState("");const [source,setSource]=useState("all");const [exported,setExported]=useState("");const filtered=data.history.filter(x=>(source==="all"||x.source===source)&&x.text.toLowerCase().includes(query.toLowerCase()));return <div className="page"><PageHead eyebrow="Library" title="Transcription history" copy="Every dictation, saved locally. Search, copy, refine, or export." action={<div className="head-actions"><Button kind="secondary" onClick={async()=>setExported(await bridge.exportHistory())}><ExternalLink size={14}/>Export</Button><Button kind="ghost" onClick={async()=>{if(confirm("Clear all transcription history?")){await bridge.clearHistory();reload()}}}><Trash2 size={14}/>Clear</Button></div>}/>{exported&&<div className="export-note"><Check size={13}/>Saved to {exported}</div>}<div className="toolbar"><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transcriptions"/></label><div className="segmented compact"><button className={source==="all"?"active":""} onClick={()=>setSource("all")}>All</button><button className={source==="local"?"active":""} onClick={()=>setSource("local")}>Local</button><button className={source==="cloud"?"active":""} onClick={()=>setSource("cloud")}>Cloud</button></div></div>{filtered.length?<div className="history-list">{filtered.map(item=><HistoryRow key={item.id} item={item} reload={reload}/>)}</div>:<Empty icon={FileText} title="No matching transcriptions" copy="Try another search or dictate something new."/>}</div>}
function HistoryRow({item,reload}:{item:HistoryItem;reload:()=>Promise<void>}){const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const rewrite=async(mode:"polish"|"enhance")=>{setBusy(true);try{await bridge.polishText(item.id,mode);await reload()}finally{setBusy(false)}};return <article className={`history-row ${open?"open":""}`}><button className="row-main" onClick={()=>setOpen(!open)}><span className="source-badge">{item.source==="local"?<Moon size={13}/>:<Cloud size={13}/>}</span><div><p>{item.text}</p><small>{new Date(item.timestamp).toLocaleString()} · {item.wordCount} words · {item.durationSeconds.toFixed(1)}s · {item.transcriptionMs}ms</small></div><ChevronDown size={16}/></button>{open&&<div className="row-actions"><Button kind="ghost" onClick={()=>bridge.copyText(item.text)}><Copy size={13}/>Copy</Button><Button kind="ghost" disabled={busy} onClick={()=>rewrite("polish")}><WandSparkles size={13}/>Polish</Button><Button kind="ghost" disabled={busy} onClick={()=>rewrite("enhance")}><Sparkles size={13}/>Enhance prompt</Button><Button kind="danger" onClick={async()=>{await bridge.deleteHistory(item.id);reload()}}><Trash2 size={13}/>Delete</Button></div>}</article>}

function StatsPage({data}:{data:RuntimeSnapshot}){const s=data.stats;const words=Array(12).fill(0) as number[];const week=7*24*3600_000;data.history.forEach(item=>{const ago=Math.floor((Date.now()-item.timestamp)/week);if(ago>=0&&ago<12)words[11-ago]+=item.wordCount});const max=Math.max(1,...words);return <div className="page"><PageHead eyebrow="Insights" title="Your voice, in numbers." copy="A private view of how much typing you have skipped."/><div className="stats-grid"><Stat label="Total words" value={s.totalWords.toLocaleString()} note={`${s.todayWords} today`} icon={FileText}/><Stat label="Speaking time" value={formatTime(s.totalSeconds)} note="Across all sessions" icon={Volume2}/><Stat label="Sessions" value={s.totalSessions.toString()} note={`${s.weekWords} words this week`} icon={Activity}/><Stat label="Average pace" value={`${s.averageWpm}`} suffix="WPM" note="Natural speaking speed" icon={Gauge}/></div><section className="card chart-card"><div className="card-title"><span>Words over time</span><small>LAST 12 WEEKS</small></div><div className="chart"><div className="chart-lines"><i/><i/><i/><i/></div>{words.map((value,i)=><span key={i} title={`${value} words`} style={{height:`${Math.max(2,value/max*100)}%`}}><b>{value}</b></span>)}</div><div className="chart-axis"><span>12 weeks ago</span><span>This week</span></div></section><section className="stats-bottom"><div className="card milestone"><span className="big-glyph">Aa</span><h3>{Math.max(0,s.totalWords*6).toLocaleString()}</h3><p>keystrokes avoided</p></div><div className="card milestone"><span className="big-glyph"><Zap size={28}/></span><h3>{Math.round(s.totalWords/40)}</h3><p>minutes saved</p></div><div className="card milestone"><span className="big-glyph"><Mic size={28}/></span><h3>{s.totalSessions}</h3><p>ideas captured</p></div></section></div>}
function Stat({label,value,note,icon:Icon,suffix}:{label:string;value:string;note:string;icon:typeof Home;suffix?:string}){return <article className="stat-card"><span><Icon size={18}/></span><small>{label}</small><strong>{value}{suffix&&<em>{suffix}</em>}</strong><p>{note}</p></article>}

function DictionaryPage({data,reload,patch}:{data:RuntimeSnapshot;reload:()=>Promise<void>;patch:(x:Partial<AppConfig>)=>Promise<void>}){const [open,setOpen]=useState(false);const [original,setOriginal]=useState("");const [replacement,setReplacement]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();if(!original.trim()||!replacement.trim())return;await bridge.addDictionary(original.trim(),replacement.trim());setOriginal("");setReplacement("");setOpen(false);reload()};return <div className="page"><PageHead eyebrow="Vocabulary" title="Custom dictionary" copy="Teach Bee the names, tools, and technical terms you use." action={<Button onClick={()=>setOpen(true)}><Plus size={14}/>Add replacement</Button>}/><section className="setting-card dictionary-toggle"><div><span className="setting-icon"><BookOpen size={17}/></span><div><strong>Apply dictionary replacements</strong><p>Automatically correct recognized phrases after transcription.</p></div></div><Switch checked={data.config.dictionaryEnabled} onChange={v=>patch({dictionaryEnabled:v})} label="Apply dictionary replacements"/></section>{open&&<form className="add-dictionary" onSubmit={submit}><label><span>When Bee hears</span><input autoFocus value={original} onChange={e=>setOriginal(e.target.value)} placeholder="e.g. next js"/></label><span className="arrow">→</span><label><span>Replace it with</span><input value={replacement} onChange={e=>setReplacement(e.target.value)} placeholder="e.g. Next.js"/></label><Button type="submit">Save</Button><Button type="button" kind="ghost" onClick={()=>setOpen(false)}>Cancel</Button></form>}<div className="dictionary-table"><div className="table-head"><span>Spoken phrase</span><span>Replacement</span><span>Added</span><span/></div>{data.dictionary.map(entry=><DictionaryRow entry={entry} key={entry.id} reload={reload}/>)}</div>{!data.dictionary.length&&<Empty icon={BookOpen} title="Your dictionary is empty" copy="Add a phrase that speech models often miss."/>}</div>}
function DictionaryRow({entry,reload}:{entry:DictionaryEntry;reload:()=>Promise<void>}){return <div className="table-row"><span>“{entry.original}”</span><strong>{entry.replacement}</strong><small>{new Date(entry.createdAt).toLocaleDateString()}</small><button onClick={async()=>{await bridge.deleteDictionary(entry.id);reload()}}><Trash2 size={14}/></button></div>}

function ShortcutsPage({data,patch}:{data:RuntimeSnapshot;patch:(x:Partial<AppConfig>)=>Promise<void>}){const [capturing,setCapturing]=useState<"ptt"|"toggle"|null>(null);useEffect(()=>{if(!capturing)return;const fn=(e:KeyboardEvent)=>{e.preventDefault();const keys=[e.metaKey&&"⌘",e.ctrlKey&&"⌃",e.altKey&&"⌥",e.shiftKey&&"⇧",!['Meta','Control','Alt','Shift'].includes(e.key)&&e.key.toUpperCase()].filter(Boolean).join(" ");if(keys){patch(capturing==="ptt"?{pushToTalkKey:keys}:{toggleKey:keys});setCapturing(null)}};window.addEventListener("keydown",fn,{capture:true});return()=>window.removeEventListener("keydown",fn,{capture:true})},[capturing]);return <div className="page"><PageHead eyebrow="Controls" title="Shortcuts" copy="Bee stays out of the way until you call for it."/><section className="recommended-callout"><span className="globe">◎</span><div><small>RECOMMENDED FOR THIS MAC</small><h3>Use Fn / Globe for push-to-talk</h3><p>It is easy to hold, works in every app, and never conflicts with typing.</p></div><Button onClick={()=>patch({pushToTalkKey:"Fn / Globe"})}>{data.config.pushToTalkKey==="Fn / Globe"?<><Check size={14}/>Recommended active</>:"Use recommended"}</Button></section><div className="settings-stack"><SettingGroup title="Recording shortcuts" copy="Set one or both. Push-to-talk may use a modifier-only key."><ShortcutRow title="Push to talk" copy="Hold to record, release to transcribe." value={data.config.pushToTalkKey} capturing={capturing==="ptt"} onClick={()=>setCapturing("ptt")}/><ShortcutRow title="Toggle recording" copy="Press once to start, again to finish." value={data.config.toggleKey||"Not set"} capturing={capturing==="toggle"} onClick={()=>setCapturing("toggle")}/></SettingGroup><SettingGroup title="Shortcut behavior"><SettingRow title="Pause shortcuts" copy="Temporarily disable global recording keys."><Switch checked={data.config.shortcutsPaused} onChange={v=>patch({shortcutsPaused:v})} label="Pause shortcuts"/></SettingRow><SettingRow title="Cancel recording" copy="Discard the current recording without transcribing."><Kbd>Esc</Kbd></SettingRow></SettingGroup></div></div>}
function ShortcutRow({title,copy,value,capturing,onClick}:{title:string;copy:string;value:string;capturing:boolean;onClick:()=>void}){return <div className="setting-row"><div><strong>{title}</strong><p>{copy}</p></div><button className={`shortcut-capture ${capturing?"capturing":""}`} onClick={onClick}>{capturing?"Press shortcut…":<Kbd>{value}</Kbd>}</button></div>}

function SettingsPage({data,patch}:{data:RuntimeSnapshot;patch:(x:Partial<AppConfig>)=>Promise<void>}){const c=data.config;const [tab,setTab]=useState("recording");const [groq,setGroq]=useState("");return <div className="page"><PageHead eyebrow="Preferences" title="Settings" copy="Tune recording, output, audio, appearance, and privacy."/><div className="settings-tabs">{["recording","audio","widget","appearance","advanced"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="settings-stack">
  {tab==="recording"&&<><SettingGroup title="Recording behavior"><SettingRow title="Output destination" copy="Choose whether text is pasted automatically or left on your clipboard."><Select label="Output destination" value={c.copyToClipboard?"copy":"paste"} onChange={v=>patch({copyToClipboard:v==="copy"})}><option value="paste">Paste at cursor</option><option value="copy">Copy to clipboard</option></Select></SettingRow><SettingRow title="Auto enhance prompt" copy="Rewrite each dictation into a polished AI prompt. Falls back to your exact words."><Switch checked={c.autoEnhancePrompt} onChange={v=>patch({autoEnhancePrompt:v})} label="Auto enhance prompt"/></SettingRow><SettingRow title="Remove filler words" copy="Strip common fillers such as um, uh, and you know."><Switch checked={c.removeFillers} onChange={v=>patch({removeFillers:v})} label="Remove filler words"/></SettingRow><SettingRow title="Automatic punctuation" copy="Add punctuation and capitalization to local transcripts."><Switch checked={c.autoPunctuation} onChange={v=>patch({autoPunctuation:v})} label="Automatic punctuation"/></SettingRow><SettingRow title="Recording chimes" copy="Play a quiet cue when recording starts and stops."><Switch checked={c.recordingSoundEnabled} onChange={v=>patch({recordingSoundEnabled:v})} label="Recording chimes"/></SettingRow></SettingGroup><SettingGroup title="Prompt enhancement"><label className="textarea-setting"><span><strong>Custom instructions</strong><p>Tell the enhancer how you prefer prompts and prose to be shaped.</p></span><textarea value={c.customInstructions} onChange={e=>patch({customInstructions:e.target.value})} placeholder="Example: Keep code requests concise. Preserve technical names exactly."/></label></SettingGroup></>}
  {tab==="audio"&&<><SettingGroup title="Microphone"><SettingRow title="Preferred input" copy="Bee will try this device first."><Select label="Preferred microphone" value={c.preferredInputDevice||"default"} onChange={v=>patch({preferredInputDevice:v==="default"?null:v})}><option value="default">System default</option>{data.audioDevices.map(d=><option value={d.name} key={d.name}>{d.name}</option>)}</Select></SettingRow><SettingRow title="Fallback input" copy="Used automatically if the preferred microphone is silent."><Select label="Fallback microphone" value={c.fallbackInputDevice||"auto"} onChange={v=>patch({fallbackInputDevice:v==="auto"?null:v})}><option value="auto">Automatic</option>{data.audioDevices.map(d=><option value={d.name} key={d.name}>{d.name}</option>)}</Select></SettingRow><label className="range-setting"><span><strong>Input gain</strong><p>Boost quiet microphones before transcription.</p></span><div><input type="range" min="0.5" max="2" step="0.05" value={c.inputGain} onChange={e=>patch({inputGain:Number(e.target.value)})}/><b>{Math.round(c.inputGain*100)}%</b></div></label></SettingGroup></>}
  {tab==="widget"&&<SettingGroup title="Widget appearance"><SettingRow title="Show floating widget" copy="Keep a compact recording control above other windows."><Switch checked={c.showWidget} onChange={v=>patch({showWidget:v})} label="Show floating widget"/></SettingRow><SettingRow title="Auto-hide when idle" copy="Reveal the widget only while push-to-talk is held."><Switch checked={c.autoHideWidget} onChange={v=>patch({autoHideWidget:v})} label="Auto-hide widget"/></SettingRow><SettingRow title="Follow cursor to monitor" copy="Move to the display where you are actively working."><Switch checked={c.followCursor} onChange={v=>patch({followCursor:v})} label="Follow cursor"/></SettingRow><SettingRow title="Lock position" copy="Prevent accidental dragging."><Switch checked={c.lockWidgetPosition} onChange={v=>patch({lockWidgetPosition:v})} label="Lock widget position"/></SettingRow></SettingGroup>}
  {tab==="appearance"&&<SettingGroup title="Theme"><div className="theme-picker"><ThemeCard theme="black" current={c.theme} onClick={()=>patch({theme:"black"})}/><ThemeCard theme="light" current={c.theme} onClick={()=>patch({theme:"light"})}/></div></SettingGroup>}
  {tab==="advanced"&&<><SettingGroup title="Cloud transcription"><SettingRow title="Groq API key" copy={c.groqApiKeyConfigured?"A key is securely stored in your system keychain.":"Use your own key for private, direct cloud transcription."}><form className="key-form" onSubmit={async e=>{e.preventDefault();await bridge.setGroqKey(groq);setGroq("")}}><input type="password" value={groq} onChange={e=>setGroq(e.target.value)} placeholder={c.groqApiKeyConfigured?"Key configured":"gsk_…"}/><Button type="submit" kind="secondary">Save</Button></form></SettingRow><SettingRow title="Language" copy="Auto-detect, or pin a language for short and ambiguous recordings."><Select label="Cloud language" value={c.cloudLanguage} onChange={v=>patch({cloudLanguage:v})}>{[["auto","Auto detect"],["en","English"],["es","Spanish"],["fr","French"],["de","German"],["it","Italian"],["pt","Portuguese"],["nl","Dutch"],["pl","Polish"],["ru","Russian"],["uk","Ukrainian"],["tr","Turkish"],["ar","Arabic"],["hi","Hindi"],["zh","Chinese"],["ja","Japanese"],["ko","Korean"],["vi","Vietnamese"],["id","Indonesian"],["th","Thai"]].map(([code,label])=><option value={code} key={code}>{label}</option>)}</Select></SettingRow></SettingGroup><SettingGroup title="System"><SettingRow title="Launch at login" copy="Start Bee silently in the menu bar."><Switch checked={c.launchAtLogin} onChange={v=>patch({launchAtLogin:v})} label="Launch at login"/></SettingRow><SettingRow title="Quit Bee" copy="Stop shortcuts, audio capture, widget, and tray process."><Button kind="danger" onClick={()=>bridge.quitApp()}>Quit Bee</Button></SettingRow></SettingGroup></>}
  </div></div>}
function SettingGroup({title,copy,children}:{title:string;copy?:string;children:React.ReactNode}){return <section className="setting-group"><header><h2>{title}</h2>{copy&&<p>{copy}</p>}</header><div>{children}</div></section>}
function SettingRow({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <div className="setting-row"><div><strong>{title}</strong><p>{copy}</p></div>{children}</div>}
function ThemeCard({theme,current,onClick}:{theme:Theme;current:Theme;onClick:()=>void}){return <button className={`theme-card ${theme} ${current===theme?"selected":""}`} onClick={onClick}><span className="theme-preview"><i/><i/><i/></span><strong>{theme==="black"?<><Moon size={14}/>Black</>:<><Sun size={14}/>Light</>}</strong>{current===theme&&<Check size={15}/>}</button>}

function SubscriptionPage(){return <div className="page"><PageHead eyebrow="Plan & credits" title="Subscription" copy="Local dictation is free forever. Cloud intelligence runs on credits."/><section className="plan-hero"><div><small>CURRENT PLAN</small><h2>Free</h2><p>Unlimited on-device transcription with every local model.</p></div><span><b>1,250</b><small>CREDITS AVAILABLE</small></span></section><div className="plan-grid"><article className="plan-card current"><span>FREE</span><h3>$0</h3><p>Private local dictation for everyone.</p><ul><li><Check size={13}/>All on-device models</li><li><Check size={13}/>History, stats & dictionary</li><li><Check size={13}/>Push-to-talk and toggle</li></ul><Button kind="ghost" disabled>Current plan</Button></article><article className="plan-card featured"><span>PRO</span><h3>$20<small>/month</small></h3><p>Cloud dictation and AI rewrites.</p><ul><li><Check size={13}/>Everything in Free</li><li><Check size={13}/>99+ cloud languages</li><li><Check size={13}/>Polish & Enhance Prompt</li></ul><Button>Upgrade to Pro</Button></article></div></div>}
function SuggestionsPage({data,patch,reload}:{data:RuntimeSnapshot;patch:(x:Partial<AppConfig>)=>Promise<void>;reload:()=>Promise<void>}){const suggestions=useMemo(()=>findSuggestions(data),[data.history,data.dictionary,data.config.dismissedSuggestions]);return <div className="page"><PageHead eyebrow="Learning" title="Suggestions" copy="Bee notices likely corrections without changing your dictionary behind your back."/><section className="card suggestion-intro"><span><Sparkles size={21}/></span><div><h3>{suggestions.length?`${suggestions.length} correction${suggestions.length===1?"":"s"} to review`:"Nothing to review"}</h3><p>Possible acronyms and product names are inferred locally from your dictation history.</p></div></section>{suggestions.length?<div className="suggestion-list">{suggestions.map(item=><article className="setting-card dictionary-toggle" key={item.original}><div><span className="setting-icon"><Lightbulb size={17}/></span><div><strong>“{item.original}” → “{item.replacement}”</strong><p>Found in your recent dictation. Add this correction to the custom dictionary?</p></div></div><span className="suggestion-actions"><Button kind="ghost" onClick={()=>patch({dismissedSuggestions:[...data.config.dismissedSuggestions,item.original]})}>Dismiss</Button><Button onClick={async()=>{await bridge.addDictionary(item.original,item.replacement);await reload()}}>Add correction</Button></span></article>)}</div>:<Empty icon={Lightbulb} title="Bee is listening for patterns" copy="Suggestions stay local until you accept or dismiss them."/>}</div>}

function AboutPage({version}:{version:string}){const [whatsNew,setWhatsNew]=useState(false);const [update,setUpdate]=useState<UpdateInfo|null>(null);const [checking,setChecking]=useState(false);const check=async()=>{setChecking(true);try{setUpdate(await bridge.checkForUpdates())}finally{setChecking(false)}};return <div className="page"><PageHead eyebrow="Bee" title="About" copy="Privacy-first dictation for people who build software."/><section className="about-hero"><Logo/><p>Hold. Speak. Release. Land.</p><small>Version {version}</small></section><div className="about-links"><button onClick={()=>setWhatsNew(true)}>What&apos;s new <Sparkles size={14}/></button><button onClick={check}>{checking?"Checking…":"Check for updates"}<Download size={14}/></button><button onClick={()=>bridge.openExternal("https://github.com/sterlingdigitalp/bee#readme")}>Documentation <ExternalLink size={14}/></button><button onClick={()=>bridge.openExternal("https://github.com/sterlingdigitalp/bee/issues/new")}>Report issue <ExternalLink size={14}/></button></div>{update&&<section className="update-result"><span className={update.available?"available":"current"}>{update.available?<Download size={16}/>:<Check size={16}/>}</span><div><strong>{update.available?`Bee ${update.latestVersion} is available`:`You’re on ${update.currentVersion}`}</strong><p>{update.notes||"You have the newest available build."}</p></div>{update.available&&update.downloadUrl&&<Button onClick={()=>bridge.openExternal(update.downloadUrl!)}>Download update</Button>}<button onClick={()=>setUpdate(null)} aria-label="Dismiss"><X size={14}/></button></section>}{whatsNew&&<div className="modal-backdrop" role="presentation" onClick={()=>setWhatsNew(false)}><section className="close-modal whats-new" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><span className="setting-icon"><Sparkles size={19}/></span><h2>What&apos;s new in {version}</h2><ul><li><Check size={13}/>Seven downloadable local Whisper and Parakeet models</li><li><Check size={13}/>Groq cloud dictation, Polish, and Enhance Prompt</li><li><Check size={13}/>Fn / Globe, live custom shortcuts, and toggle recording</li><li><Check size={13}/>Smart microphone fallback and cursor-following widget</li><li><Check size={13}/>Local suggestions, history export, statistics, and themes</li></ul><Button onClick={()=>setWhatsNew(false)}>Got it</Button></section></div>}</div>}

function Onboarding({data,onDone}:{data:RuntimeSnapshot;onDone:()=>void}){const [step,setStep]=useState(0);const [permissions,setPermissions]=useState({microphone:false,inputMonitoring:false,accessibility:false});useEffect(()=>{bridge.checkPermissions().then(setPermissions)},[]);const grant=async()=>setPermissions(await bridge.requestPermissions());const steps=[{title:"Your voice, everywhere.",copy:"Bee turns speech into text inside any app — privately, quickly, and without breaking your flow."},{title:"A few permissions, one time.",copy:"Microphone captures your voice. Input Monitoring sees Fn / Globe. Accessibility pastes text into the app you were using."},{title:"Choose where transcription runs.",copy:"Stay fully offline with a local model, or use cloud mode for 99+ languages."},{title:"Hold one key. That’s it.",copy:"Fn / Globe is the recommended push-to-talk key on this Mac."},{title:"You’re ready to dictate.",copy:"Bee will keep running in the menu bar when the dashboard is closed."}];return <div className="onboarding"><div className="onboarding-glow"/><header><Logo/><span>{step+1} / {steps.length}</span></header><main><div className="onboarding-visual">{step===0&&<WaveHero/>}{step===1&&<div className="permission-grid">{[["Microphone",permissions.microphone],["Input Monitoring",permissions.inputMonitoring],["Accessibility",permissions.accessibility]].map(([name,ok])=><div key={String(name)} className={ok?"done":""}><ShieldCheck size={18}/><span>{name}</span>{ok?<Check size={14}/>:<i/>}</div>)}<Button onClick={grant}>{Object.values(permissions).every(Boolean)?"Permissions ready":"Grant permissions"}</Button></div>}{step===2&&<div className="mode-choice"><button className="chosen"><Moon/><strong>On-device</strong><small>Private · Offline</small><Check/></button><button><Cloud/><strong>Cloud</strong><small>99+ languages</small></button></div>}{step===3&&<div className="key-demo"><kbd>fn</kbd><span>Hold to talk</span></div>}{step===4&&<div className="ready-check"><Check size={42}/></div>}</div><span className="eyebrow">{["WELCOME TO BEE","SYSTEM ACCESS","TRANSCRIPTION","PUSH TO TALK","ALL SET"][step]}</span><h1>{steps[step].title}</h1><p>{steps[step].copy}</p>{step===2&&<small className="setup-note">You can change this any time in Settings.</small>}{step===3&&<div className="shortcut-summary"><span>Recommended</span><Kbd>{data.config.pushToTalkKey}</Kbd></div>}</main><footer><button className="skip-onboarding" onClick={onDone}>Skip setup</button><div className="step-dots">{steps.map((_,i)=><i className={i===step?"active":""} key={i}/>)}</div><Button onClick={()=>step===steps.length-1?onDone():setStep(step+1)}>{step===steps.length-1?"Open Bee":"Continue"}</Button></footer></div>}
function WaveHero(){return <div className="wave-hero">{Array.from({length:23},(_,i)=><i key={i} style={{height:`${18+Math.abs(Math.sin(i*.72))*70}%`}}/> )}<span className="wave-cursor"/></div>}
function Empty({icon:Icon,title,copy}:{icon:typeof Home;title:string;copy:string}){return <div className="empty"><span><Icon size={21}/></span><strong>{title}</strong><p>{copy}</p></div>}
function relative(t:number){const m=Math.floor((Date.now()-t)/60000);if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`}
function formatTime(s:number){if(s<60)return `${Math.round(s)}s`;const m=Math.floor(s/60);return m<60?`${m}m`:`${Math.floor(m/60)}h ${m%60}m`}
